/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CycleForm: typeof import('./src/components/CycleForm.vue')['default']
    CycleLineChart: typeof import('./src/components/CycleLineChart.vue')['default']
    CycleList: typeof import('./src/components/CycleList.vue')['default']
    FlowHeatmap: typeof import('./src/components/FlowHeatmap.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SymptomBarChart: typeof import('./src/components/SymptomBarChart.vue')['default']
  }
}
